development:
  cloud_name: dashy
  api_key: '219441847515364'
  api_secret: fbOQxgozjYG2acAMKi3FYL61LOI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dashy
  api_key: '219441847515364'
  api_secret: fbOQxgozjYG2acAMKi3FYL61LOI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dashy
  api_key: '219441847515364'
  api_secret: fbOQxgozjYG2acAMKi3FYL61LOI
  enhance_image_tag: true
  static_image_support: false
